name: Hide PNG from Code Review

on:
  pull_request:
    types: [opened]

jobs:
  hide-png-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Fetch latest changes from the remote repository
      - name: Fetch latest changes
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      # Rebase local changes on top of the remote branch
      - name: Rebase local changes
        run: git rebase origin/${{ github.base_ref }}

      # Exclude PNG files from code review
      - name: Exclude PNG files from code review
        run: |
          find . -name '*.png' -exec git rm --cached {} +

      # Commit changes with appropriate message
      - name: Commit changes
        run: |
          git add .
          git commit -m "Exclude PNG files from code review" || echo "No changes to commit"

      # Push changes back to the pull request branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
