name: Hide Images from PR Preview

on:
  pull_request:
    types: [opened]

jobs:
  hide-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout the head SHA of the pull request

      - name: Exclude images from diff
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          BEFORE_SHA=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}) # Get the base commit SHA of the pull request
          git diff --name-only $BEFORE_SHA ${{ github.event.pull_request.head.sha }} | grep -E '\.png$|\.jpg$|\.jpeg$|\.gif$' | xargs -I{} git reset HEAD {}

      - name: Commit changes
        run: |
          git add .
          git commit -m "Exclude images from PR preview" || echo "No changes to commit"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
