name: Hide Images from PR Preview

on:
  pull_request:
    types: [opened]

jobs:
  hide-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get base and head SHAs
        id: get-shas
        run: |
          BASE_SHA=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "::set-output name=base_sha::$BASE_SHA"
          echo "::set-output name=head_sha::${{ github.event.pull_request.head.sha }}"

      - name: Exclude images from diff
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          BEFORE_SHA=${{ steps.get-shas.outputs.base_sha }}
          HEAD_SHA=${{ steps.get-shas.outputs.head_sha }}
          git diff --name-only $BEFORE_SHA $HEAD_SHA | grep -E '\.png$|\.jpg$|\.jpeg$|\.gif$' | xargs -I{} git reset HEAD {}

      - name: Commit changes
        run: |
          git add .
          git commit -m "Exclude images from PR preview" || echo "No changes to commit"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
