name: Hide PNG from Code Review

on:
  pull_request:
    types: [opened]

jobs:
  hide-png-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Exclude PNG files from code review
      - name: Exclude PNG files from code review
        run: |
          find ./node_modules -name '*.png' -exec git rm --cached {} +

      # Configure Git user
      - name: Set Git user
        run: |
          git config --global user.email "${{ github.event.pull_request.user.email }}"
          git config --global user.name "${{ github.event.pull_request.user.login }}"

      # Explicitly stage changes
      - name: Stage changes
        run: |
          git add -u

      # Commit changes with appropriate message
      - name: Commit changes
        run: |
          git commit -m "Exclude PNG files from code review" || echo "No changes to commit"

      # Push changes back to the pull request branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
