name: Hide Images from PR Preview

on:
  pull_request:
    types: [opened]

jobs:
  hide-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # Check out the branch specified by github.head_ref

      - name: Exclude images from diff
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.png$|\.jpg$|\.jpeg$|\.gif$' | xargs -I{} git reset HEAD {}

      - name: Commit changes
        run: |
          git add .
          git commit -m "Exclude images from PR preview" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
